spring:
  redis:
    host: 127.0.0.1
    port: 3306
  datasource:
    url: jdbc:mysql://localhost
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true