spring:
  datasource:
    url: jdbc:mysql://localhost
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  openweathermap:
    key: 26e6db5cc66e5d8ed4e2aacde0f32af8
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
logging:
  config: classpath:logback-spring.xml